// Авторизация
export const SET_USER_DATA = 'SET_USER_DATA';
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';
export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';

// Сотрудники
export const EMPLOYEES_GET_REQUEST = 'EMPLOYEES_GET_REQUEST';
export const EMPLOYEES_GET_SUCCESS = 'EMPLOYEES_GET_SUCCESS';
export const EMPLOYEES_GET_ERROR = 'EMPLOYEES_GET_ERROR';
export const EMPLOYEE_ADD_REQUEST = 'EMPLOYEE_ADD_REQUEST';
export const EMPLOYEE_ADD_SUCCESS = 'EMPLOYEE_ADD_SUCCESS';
export const EMPLOYEE_ADD_ERROR = 'EMPLOYEE_ADD_ERROR';
export const EMPLOYEE_DELETE_REQUEST = 'EMPLOYEE_DELETE_REQUEST';
export const EMPLOYEE_DELETE_SUCCESS = 'EMPLOYEE_DELETE_SUCCESS';
export const EMPLOYEE_DELETE_ERROR = 'EMPLOYEE_DELETE_ERROR';

// Информация о сотруднике
export const EMPLOYEE_INFO_GET_REQUEST = 'EMPLOYEE_INFO_GET_REQUEST';
export const EMPLOYEE_INFO_GET_SUCCESS = 'EMPLOYEE_INFO_GET_SUCCESS';
export const EMPLOYEE_INFO_GET_ERROR = 'EMPLOYEE_INFO_GET_ERROR';
export const EMPLOYEE_INFO_UPDATE_REQUEST = 'EMPLOYEE_INFO_UPDATE_REQUEST';
export const EMPLOYEE_INFO_UPDATE_SUCCESS = 'EMPLOYEE_INFO_UPDATE_SUCCESS';
export const EMPLOYEE_INFO_UPDATE_ERROR = 'EMPLOYEE_INFO_UPDATE_ERROR';


//=========================================================
//_______________________CUSTOMER__________________________
//=========================================================

//_______________________ФИЗИЧЕСКИЕ ЛИЦА__________________________
export const SET_SEARCH_INDIVIDUALS = 'SET_SEARCH_INDIVIDUALS';

// Запрос Физ. лиц по поиску
export const GET_SEARCH_INDIVIDUALS_REQUEST = 'GET_SEARCH_INDIVIDUALS_REQUEST';
export const GET_SEARCH_INDIVIDUALS_SUCCESS = 'GET_SEARCH_INDIVIDUALS_SUCCESS';
export const GET_SEARCH_INDIVIDUALS_ERROR = 'GET_SEARCH_INDIVIDUALS_ERROR';

// Запрос данных Физ. лица по его ID
export const GET_INDIVIDUAL_DATA_REQUEST = 'GET_INDIVIDUAL_DATA_REQUEST';
export const GET_INDIVIDUAL_DATA_SUCCESS = 'GET_INDIVIDUAL_DATA_SUCCESS';
export const GET_INDIVIDUAL_DATA_ERROR = 'GET_INDIVIDUAL_DATA_ERROR';

// Запрос на добавления Физ. лица
export const INDIVIDUALS_ADD_REQUEST = 'INDIVIDUALS_ADD_REQUEST';
export const INDIVIDUALS_ADD_SUCCESS = 'INDIVIDUALS_ADD_SUCCESS';
export const INDIVIDUALS_ADD_ERROR = 'INDIVIDUALS_ADD_ERROR';

// Запрос на редактирование Физ. лица
export const INDIVIDUALS_EDIT_REQUEST = 'INDIVIDUALS_EDIT_REQUEST';
export const INDIVIDUALS_EDIT_SUCCESS = 'INDIVIDUALS_EDIT_SUCCESS';
export const INDIVIDUALS_EDIT_ERROR = 'INDIVIDUALS_EDIT_ERROR';

// Запрос на удаление Физ. лица
export const INDIVIDUALS_DELETE_REQUEST = 'INDIVIDUALS_DELETE_REQUEST';
export const INDIVIDUALS_DELETE_SUCCESS = 'INDIVIDUALS_DELETE_SUCCESS';
export const INDIVIDUALS_DELETE_ERROR = 'INDIVIDUALS_DELETE_ERROR';

//_______________________Охотничий билет__________________________
// Запрос охотничих билетов
export const GET_HUNTING_LICENSE_REQUEST = 'GET_HUNTING_LICENSE_REQUEST';
export const GET_HUNTING_LICENSE_SUCCESS = 'GET_HUNTING_LICENSE_SUCCESS';
export const GET_HUNTING_LICENSE_ERROR = 'GET_HUNTING_LICENSE_ERROR';

// Запрос на добавление билета
export const ADD_HUNTING_LICENSE_REQUEST = 'ADD_HUNTING_LICENSE_REQUEST';
export const ADD_HUNTING_LICENSE_SUCCESS = 'ADD_HUNTING_LICENSE_SUCCESS';
export const ADD_HUNTING_LICENSE_ERROR = 'ADD_HUNTING_LICENSE_ERROR';

// Запрос на редактирование билета
export const EDIT_HUNTING_LICENSE_REQUEST = 'EDIT_HUNTING_LICENSE_REQUEST';
export const EDIT_HUNTING_LICENSE_SUCCESS = 'EDIT_HUNTING_LICENSE_SUCCESS';
export const EDIT_HUNTING_LICENSE_ERROR = 'EDIT_HUNTING_LICENSE_ERROR';

// Запрос на удаление билета
export const DELETE_HUNTING_LICENSE_REQUEST = 'DELETE_HUNTING_LICENSE_REQUEST';
export const DELETE_HUNTING_LICENSE_SUCCESS = 'DELETE_HUNTING_LICENSE_SUCCESS';
export const DELETE_HUNTING_LICENSE_ERROR = 'DELETE_HUNTING_LICENSE_ERROR';


//_______________________Разрешение на охоту__________________________
// Запрос разрешений
export const GET_HUNTING_PERMISSION_REQUEST = 'GET_HUNTING_PERMISSION_REQUEST';
export const GET_HUNTING_PERMISSION_SUCCESS = 'GET_HUNTING_PERMISSION_SUCCESS';
export const GET_HUNTING_PERMISSION_ERROR = 'GET_HUNTING_PERMISSION_ERROR';

// Запрос на добавление разрешения
export const ADD_HUNTING_PERMISSION_REQUEST = 'ADD_HUNTING_PERMISSION_REQUEST';
export const ADD_HUNTING_PERMISSION_SUCCESS = 'ADD_HUNTING_PERMISSION_SUCCESS';
export const ADD_HUNTING_PERMISSION_ERROR = 'ADD_HUNTING_PERMISSION_ERROR';

// Запрос на редактирование разрешения
export const EDIT_HUNTING_PERMISSION_REQUEST = 'EDIT_HUNTING_PERMISSION_REQUEST';
export const EDIT_HUNTING_PERMISSION_SUCCESS = 'EDIT_HUNTING_PERMISSION_SUCCESS';
export const EDIT_HUNTING_PERMISSION_ERROR = 'EDIT_HUNTING_PERMISSION_ERROR';

// Запрос на удаление разрешения
export const DELETE_HUNTING_PERMISSION_REQUEST = 'DELETE_HUNTING_PERMISSION_REQUEST';
export const DELETE_HUNTING_PERMISSION_SUCCESS = 'DELETE_HUNTING_PERMISSION_SUCCESS';
export const DELETE_HUNTING_PERMISSION_ERROR = 'DELETE_HUNTING_PERMISSION_ERROR';




//=========================================================
//_______________________REFERENCE__________________________
//=========================================================

//_______________________Охотничьи угодья__________________________
// Запрос охот. угодий
export const GET_HUNTING_FARM_REQUEST = 'GET_HUNTING_FARM_REQUEST';
export const GET_HUNTING_FARM_SUCCESS = 'GET_HUNTING_FARM_SUCCESS';
export const GET_HUNTING_FARM_ERROR = 'GET_HUNTING_FARM_ERROR';

// Запрос на добавление охот. угодий
export const ADD_HUNTING_FARM_REQUEST = 'ADD_HUNTING_FARM_REQUEST';
export const ADD_HUNTING_FARM_SUCCESS = 'ADD_HUNTING_FARM_SUCCESS';
export const ADD_HUNTING_FARM_ERROR = 'ADD_HUNTING_FARM_ERROR';

// Запрос на редактирование охот. угодий
export const EDIT_HUNTING_FARM_REQUEST = 'EDIT_HUNTING_FARM_REQUEST';
export const EDIT_HUNTING_FARM_SUCCESS = 'EDIT_HUNTING_FARM_SUCCESS';
export const EDIT_HUNTING_FARM_ERROR = 'EDIT_HUNTING_FARM_ERROR';

// Запрос на удаление охот. угодий
export const DELETE_HUNTING_FARM_REQUEST = 'DELETE_HUNTING_FARM_REQUEST';
export const DELETE_HUNTING_FARM_SUCCESS = 'DELETE_HUNTING_FARM_SUCCESS';
export const DELETE_HUNTING_FARM_ERROR = 'DELETE_HUNTING_FARM_ERROR';

//_______________________Виды охот. хозяйств__________________________
// Запрос охот. хозяйств
export const GET_HUNTING_FARM_TYPE_REQUEST = 'GET_HUNTING_FARM_TYPE_REQUEST';
export const GET_HUNTING_FARM_TYPE_SUCCESS = 'GET_HUNTING_FARM_TYPE_SUCCESS';
export const GET_HUNTING_FARM_TYPE_ERROR = 'GET_HUNTING_FARM_TYPE_ERROR';

// Запрос на добавление охот. хозяйств
export const ADD_HUNTING_FARM_TYPE_REQUEST = 'ADD_HUNTING_FARM_TYPE_REQUEST';
export const ADD_HUNTING_FARM_TYPE_SUCCESS = 'ADD_HUNTING_FARM_TYPE_SUCCESS';
export const ADD_HUNTING_FARM_TYPE_ERROR = 'ADD_HUNTING_FARM_TYPE_ERROR';

// Запрос на редактирование охот. хозяйств
export const EDIT_HUNTING_FARM_TYPE_REQUEST = 'EDIT_HUNTING_FARM_TYPE_REQUEST';
export const EDIT_HUNTING_FARM_TYPE_SUCCESS = 'EDIT_HUNTING_FARM_TYPE_SUCCESS';
export const EDIT_HUNTING_FARM_TYPE_ERROR = 'EDIT_HUNTING_FARM_TYPE_ERROR';

// Запрос на удаление охот. хозяйств
export const DELETE_HUNTING_FARM_TYPE_REQUEST = 'DELETE_HUNTING_FARM_TYPE_REQUEST';
export const DELETE_HUNTING_FARM_TYPE_SUCCESS = 'DELETE_HUNTING_FARM_TYPE_SUCCESS';
export const DELETE_HUNTING_FARM_TYPE_ERROR = 'DELETE_HUNTING_FARM_TYPE_ERROR';

//_______________________Справочник юр. лиц__________________________
// Запрос юр. лиц
export const GET_LEGAL_PERSON_REQUEST = 'GET_LEGAL_PERSON_REQUEST';
export const GET_LEGAL_PERSON_SUCCESS = 'GET_LEGAL_PERSON_SUCCESS';
export const GET_LEGAL_PERSON_ERROR = 'GET_LEGAL_PERSON_ERROR';

// Запрос на добавление юр. лица
export const ADD_LEGAL_PERSON_REQUEST = 'ADD_LEGAL_PERSON_REQUEST';
export const ADD_LEGAL_PERSON_SUCCESS = 'ADD_LEGAL_PERSON_SUCCESS';
export const ADD_LEGAL_PERSON_ERROR = 'ADD_LEGAL_PERSON_ERROR';

// Запрос на редактирование юр. лица
export const EDIT_LEGAL_PERSON_REQUEST = 'EDIT_LEGAL_PERSON_REQUEST';
export const EDIT_LEGAL_PERSON_SUCCESS = 'EDIT_LEGAL_PERSON_SUCCESS';
export const EDIT_LEGAL_PERSON_ERROR = 'EDIT_LEGAL_PERSON_ERROR';

// Запрос на удаление юр. лица
export const DELETE_LEGAL_PERSON_REQUEST = 'DELETE_LEGAL_PERSON_REQUEST';
export const DELETE_LEGAL_PERSON_SUCCESS = 'DELETE_LEGAL_PERSON_SUCCESS';
export const DELETE_LEGAL_PERSON_ERROR = 'DELETE_LEGAL_PERSON_ERROR';
